### ISSUE TITLE
Container building stalled. Manual trigger doesn't seem to fix it.

### ISSUE THREAD

**Issue by andersgs** [singularityhub/singularityhub.github.io#104]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/collections/579

### Behavior when Building Locally

Works! Built it successfully on a VM running Centos7 and the latest version of Singularity.

### Error on Singularity Hub

Just seems to sit there. Starts with "WAITING", and the other "PENDING". Then just sits on "WAITING". Because I had submitted very closely with another repo (which also seemed to have stalled), I delete the containers and then triggered the build manually (as suggested). But, that did not seem to help.

### What do you think is going on?

I am not sure. I can't seem to find any logs. These seem to appear after a build is successful. 

I really like Singularity, and the idea behind Singularity-Hub is genius. My goal is to build a large-ish collection of containers that are relevant to public health microbial genomics. From the perspective of someone that works in public health, where reproducibility and traceability are paramount, Singularity is terrific! It means my team can run locked down software without having to compromise the server's security by giving out `sudo` access to everyone! Thank you!!

**Comment by vsoch** [comment]
hey @andersgs ! I just looked into this for you - there have definitely been issues with triggering builds as a result of the google api's being pinged to remove your old running instance (and then the queue not being updated). I just changed some things around and you have a build running for the main "Singularity" file. For the second one, the build errored because you just needed to specify the folder WITH the file name (the full path like `v0.5.1/Singularity.v0.5.1` instead of just `Singularity.v0.5.1`). I'm watching the first and I will trigger this second one for you too. Stay tuned!

**Comment by vsoch** [comment]
hey just fixed one more bug :) I'm going back to sleep but I'll check this when I wake up.

**Comment by vsoch** [comment]
haha just kidding, wanted to get the second one up and running. NOW I'm going back to sleep! :sleeping:

**Comment by vsoch** [comment]
Houston we have containers!

https://www.singularity-hub.org/collections/579

Let me know if you run into any other issues or have questions! Feel free to close if resolved.

**Comment by andersgs** [comment]
That is awesome!! Thank you so much @vsoch!!! Much appreciated!!! Hope you had a good sleep.
