### ISSUE TITLE
one build stuck Running another Errored

### ISSUE THREAD

**Issue by yarikoptic** [singularityhub/singularityhub.github.io#111]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/collections/209

The Errored one used to build fine before -- I just moved recipe under a subdirectory in the git repo. Now fails with `E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)` .

Another just says Running for a while already. Built fine locally (Debian sid)

**Comment by vsoch** [comment]
Yeah I saw the container and killed it because it was running over a day! I think we will likely do best to wait for the update, but if you are able to start the container running again (and then ping me when it's been going and seems to be stuck) then I can connect to the build for some live debugging action! Sorry for the trouble, we will figure it out :)

**Comment by vsoch** [comment]
@yarikoptic ditto here, please update builder and retry, let me know how it goes. Note that you are an early tester of the update, so just fyi!

**Comment by vsoch** [comment]
No updates, closing issue.
