### ISSUE TITLE
View build log in realtime

### ISSUE THREAD

**Issue by brucemoran** [singularityhub/singularityhub.github.io#152]
## Link to Container Collection Log, Build, or Collection (in that order)

brucemoran/Exome_n-of-1

### Behavior when Building Locally

Works

### Error on Singularity Hub

Possibly stalled(?)

### What do you think is going on?

The image built locally is ~5GB, and takes ~30 mins to complete (1 thread to mirror shub builder). Possibly stalled, as I have had versions that specified 'running' for days before I deleted and retired.

It would be great to be able to see where the builder is as per local build. I have seen some instances for others where builds stalled e.g. #147 . The capacity for users to view logs in realtime would be very welcome. 

As an aside, is size of image is an issue? What general guidelines are available WRT size? I saw you recommend to others to install a framework for images, then install other tools/resources in the image locally after it is pulled. Is this documented anywhere (i.e. what to use in framework, what to do locally?). Advice on strategy to do this would be welcome also.

Thanks, Bruce.

**Comment by vsoch** [comment]
Did you test this out locally with the secure builder as we discussed in #147 ? Could you please share the complete output?

I can't give any "real time" access to the builders, that would be a huge security risk for my institution. I have also approached Google (it's on GCE) about an API to show their instance stats, but this is afaik still not available.

Yes, size can definitely be an issue! The builder is either a 50 or 100GB instance (depending on your selection in the Collection settings). The size must include:

 - 1, your original repo
 - 2. a sandbox of the build
 - 3. the squashfs built from that (in addition to the sandbox).

For most issues like yours, the instance is actually killed due to going over the disk and there is no opportunity for the builder to send a signal back. There is then a monitor that kills instances after 2 hours, so even if it appears to be running it is not.

I would suggest that you take advantage of base images if the image build time goes over, e.g.:

```
bootstrap: docker
from: collection/mybase
```
or if size is an issue, just build more modular images (less software per image). A lot of these fat images are from the neuro community trying to fit in fsl, afni, freesurfer, and it's too much. 

I'm going to close the issue here and let's please keep conersation to your original issue, I'm not sure why you opened a new one but I assure you I am notified of both! :)
