### ISSUE TITLE
"master" branch appears lost in a forest of branches - an edge case

### ISSUE THREAD

**Issue by darachm** [singularityhub/singularityhub.github.io#163]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/collections/2508/settings

### Behavior when Building Locally

Works fine!

### Error on Singularity Hub

I cannot select the "master" branch to trigger a build.

### What do you think is going on?

I want to build ( https://github.com/darachm/bartender-1.1/ ) on Singularity hub. I want to put a Singularity file in that repo to help them bake singularity into their software distribution.

This repo is a special edge case. It has 63 branches. Apparently that works for the people developing it. However, the build settings with the heading "Edit Build Branches" can't find the "master" branch to build from. Only 30 branches are listed, and master is not one of them.

I'd imagine that the singularity hub has limited listing 30 branches, not imagining that 63 branches would ever be used. I think this 63 branch forest is definitely an edge case.

Do y'all think shub should be able to handle this case, or should I just build my container by cloning the other repo (like this https://github.com/darachm/singularity_bartender) ? Please advise. Thanks for the good work and product.

**Comment by vsoch** [comment]
Oh my - this is actually a limit of the GitHub api, we don't use a paginated response because (as you suggest) it's really unlikely to have that many branches. 

Since it's an edge case, I would try simplifying things and creating a separate repo that is just for Singularity recipes. You could have, in the recipe, cloning the repo to start. That way, you don't have to deal with all those branches, and you develop the two things in a modular way.

**Comment by darachm** [comment]
Okay, makes sense. I'll close this issue to reflect that.
