### ISSUE TITLE
Is singularity down?

### ISSUE THREAD

**Issue by joaocaldeira** [singularityhub/singularityhub.github.io#167]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/collections/2968

### Behavior when Building Locally

No issues.

### Error on Singularity Hub

> We had an issue retrieving files for this container! Try another build?

For many containers, not just mine. And when trying to pull,

> FATAL:   Failed to get manifest from Shub: The requested manifest was not found in singularity hub

### What do you think is going on?

Singularity is down?

**Comment by vsoch** [comment]
Can you show me the exact command that you are using to pull? It’s very likely you just aren’t specifying an existing tag.

For the Files message, we used to send a lot of the files back to the server from the build, but we stopped doing that.  To support containers that do and do not have this, the message that you see is there

**Comment by vsoch** [comment]
This works fine for me, I think you are just forgetting the tags :)

```
$ singularity pull shub://joaocaldeira/singularity_imgs:py3_tf113
```
If your collection doesn't have a Singularity file (that builds to latest) then pull of the collection name without a tag (that defaults to latest) of course will fail. The error message is telling you exactly the truth - the manifest is not found because it doesn't exist.

**Comment by joaocaldeira** [comment]
Whoops. Thanks! I guess the files message convinced me there was an issue, so when I saw the fatal error I just continued in that path instead of checking what was wrong with my command.

**Comment by vsoch** [comment]
No worries! :)
