### ISSUE TITLE
Building with a specific Singularity Version

### ISSUE THREAD

**Issue by NotRyan** [singularityhub/singularityhub.github.io#168]
Does Singularity hub have support for building with a specific version of Singularity? For example, I'd like to build something with the container format of Singularity 2.6, but the builders seem to default to some 3.x container format.

**Comment by vsoch** [comment]
I can't support later than the current because Sylabs never provided a secure build (a custom command for Singularity to complete isolate) for it. What I've been working on (to hopefully help institutions to roll their own Singularity Hubs with whatever version builder they like) is a Singularity Registry with Google Cloud Build + GitHub integration.  The PR is here: https://github.com/singularityhub/sregistry/pull/172 and I should be opening it up for testing (so you could try it!) sometime this week. 

For your specific question, I've tried to engage with Sylabs but they are not responsive to this need. So it wouldn't hurt if you wanted to try. For the future, depending on how far Singularity gets from it's 2.* derivatives, I might switch Singularity Hub to be a Singularity Registry. Or in the case that Sylabs provides a secure build, I can update the builders. Or if they step up and provide GitHub builders to put Singularity Hub out of business? That would be even better :)

**Comment by vsoch** [comment]
And I believe current is 2.5.1 (unless you have specified otherwise in your collection settings).
