### ISSUE TITLE
Updates for 2.3

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularityhub.github.io#17]
- Builders should obviously have 2.3
- Singularity Python should be updated to provide client, with a web interface with instructions, and a command line interface to compare containers
- Builder should be modified to add metadata about build to container

**Comment by akkornel** [comment]
Can I add one?

• If the bootstrap fails during the `%test` portion, keep the container image anyway, so that the user can get to the container and check stuff out.

**Comment by vsoch** [comment]
hmm, I think it would make sense to add an option to just disable the test. I wouldn't want an image to return as being successful given that test fails, unless the user specifically asked for the build with test disabled (and thus knows about this.) Would that seem reasonable?

**Comment by akkornel** [comment]
Blargh, that's a good question.

I think, as an end user, I would at least want to see the log of the failure, to help understand what went wrong.  It would also be nice if I could get ahold of the bootstrapped-but-untested image, so that I could mount it and dig into it (that's especially helpful if my tests don't output good error messages).  But, even though I would have access to the failed image, I wouldn't want other people to get to it.

As for a "Allow failing tests?" type of setting, I'd say that they should just disable the tests in their bootstrap file.

**Comment by vsoch** [comment]
@akkornel I'm going to close the issue - the `%test` bit can be controlled by the user, and the others are all set. Feel free to open again if I'm missing something.
