### ISSUE TITLE
Webhook stopped working

### ISSUE THREAD

**Issue by chrarnold** [singularityhub/singularityhub.github.io#189]
## Link to Container Collection Log, Build, or Collection (in that order)

chrarnold/Singularity_images

### Behavior when Building Locally

The webhook worked half a year, today I did a new commit and nothing happens. 
I (re)authorized Singularity Hub 2.0 so it is properly added in my Github account, still the same

### Error on Singularity Hub

In my Github repo, this is what I get:

```Headers
Connection: keep-alive
Content-Length: 185
Content-Type: text/html
Date: Mon, 23 Sep 2019 16:21:21 GMT
Location: https://singularity-hub.org/hooks/build/push
Server: nginx/1.13.5
Body
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.13.5</center>
</body>
</html>
```

So what has been moved exactly?

### What do you think is going on?

I did not find clear information in the Documentation as to what is going on.

**Comment by vsoch** [comment]
hey @chrarnold if you look on the front page -> https://singularity-hub.org/ there is a message that you need to remove the "www" for your webhook in your repository settings - it's giving you a 301 because it's redirecting to that (and GitHub won't accept that). 

There have been quite a lot of changes since you've been here, the post that you missed about the webhooks is [here](https://singularityhub.github.io/singularityhub-docs/2019/open-for-building/) and you can read about new limits [here](https://singularityhub.github.io/singularityhub-docs/2019/release-announcement/). I posted on Twitter, on an issue here, and also emailed addresses associated with the GitHub accounts, so you must have missed all of those avenues.

**Comment by chrarnold** [comment]
Thank you a lot, and sorry for missing that! I looked in the Documentation, I suggest adding a link to this change in the section "Why isn’t my webhook working?". Thanks for the quick reply, it works now :)

**Comment by vsoch** [comment]
Sure! Could you show me where you were looking (and expected to find it?)

**Comment by chrarnold** [comment]
Yes sure! I ended up here: https://singularityhub.github.io/singularityhub-docs/docs/support/troubleshooting#why-isnt-my-webhook-working

Sorry for overseeing this, I read the news a while ago but skipped the updated webhook part.

**Comment by vsoch** [comment]
okay take a look now https://singularityhub.github.io/singularityhub-docs/docs/support/troubleshooting#why-isnt-my-webhook-working -  don't use browser cache / open new browser in case your cache is loading a previous version.

**Comment by chrarnold** [comment]
Perfect! This might save some users time and it is very clear now, thanks!

**Comment by vsoch** [comment]
Sure thing! Closing issue, happy building :)
