### ISSUE TITLE
New commit not building...

### ISSUE THREAD

**Issue by jgrn307** [singularityhub/singularityhub.github.io#191]
## Link to Container Collection Log, Build, or Collection (in that order)

https://singularity-hub.org/collections/428

### Behavior when Building Locally

N/A

### Error on Singularity Hub

Previously this was working fine, but I just did a new commit from my github repo and the container isn't building (https://github.com/gearslaboratory/gears-singularity/blob/master/singularity-definitions/specialized_use/Singularity.gears-lastools)

### What do you think is going on?

No idea!

**Comment by vsoch** [comment]
When was your last built? Have you updated the webhook since the announcement to do so? https://singularityhub.github.io/singularityhub-docs/2019/open-for-building/#webhooks

What would help is to look at your webhook settings, confirm that the URL doesn't have www, and then click on the hook to see the request and response from the server.

**Comment by vsoch** [comment]
Any updates since last year or can we close the issue?

**Comment by vsoch** [comment]
No response, closing issue.
