### ISSUE TITLE
Does singularityhub collection work with Gitlab?

### ISSUE THREAD

**Issue by lesliewubbel** [singularityhub/singularityhub.github.io#226]
Does singularityhub collection work with Gitlab?

**Comment by vsoch** [comment]
It does not.

**Comment by lesliewubbel** [comment]
Thank you! is the code base open source to extend that capability or no?

**Comment by vsoch** [comment]
Unfortunately no - I always wanted to, but since I'm the only engineer to create and ever touch the code, it made me nervous to have it out there and then allow for someone to potentially act maliciously. What I did do, however, was make an open source derivative - Singularity Registry Server, so if you wanted to deploy something like Singularity Hub (and contribute to it!) that would be an option. See https://github.com/singularityhub/sregistry.

**Comment by lesliewubbel** [comment]
I will take a crack it one day basically there is a size limit on github and LFS didn't work out as planned gitlab provides a 10.0 GB size limit. Thank you!

**Comment by vsoch** [comment]
Sure! Feel free to close the issue if I've answered your question.
