### ISSUE TITLE
improve search interface

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularityhub.github.io#39]
currently all containers are returned. Container collections should be returned, and the user browses containers from there.

**Comment by vsoch** [comment]
okay this is much improved:

![image](https://user-images.githubusercontent.com/814322/27989486-a91876e6-6407-11e7-9e12-7620d15543fd.png)

the containers aren't searched, but rather the collections. The most relevant information that the user might want is returned - including tags (clicking takes to other containers tagged similarity) the collection itself with containers, and the Github repo. @alaindomissy pinging you to know since I think you brought this up (and it was a great fix!) This will be available in the next release.

**Comment by vsoch** [comment]
one more tweak - having the collection name twice is sort of redundant, so I changed it to be the container count: 
![image](https://user-images.githubusercontent.com/814322/27989513-31038780-6408-11e7-9c93-57c66d87a945.png)

**Comment by alaindomissy** [comment]
This is much better. But I am still unsure when should people use the magnifying glass to to a search, and when they should click on "Containers" and fill up the "Enter keywords here" box. Why not lead to the same   page and display output in the same format ? The "Containers/Enter keywords here" page seems much nicer and more useful to me. Am I missing something ? If the 2 searches are indeed different in he way they work and in the output they return , could they be merged into a page that offer both search strategies or at least have the 2 pages mentioned each other ? Ok ... I am just saying since you asked... But the fix as it is is already pretty good. Thanks.

**Comment by vsoch** [comment]
The box under "Containers" isn't a search implemented by the back end server, it's just a filter of the table. That makes sense to me to be where the user goes when he/she is generally browsing, first. Then when looking for something specific (and wanting to search via the server) that is when you would want to use the actual search.

**Comment by alaindomissy** [comment]
OK. So what  showing "Filter" before the "Enter keywords box" the Containers page.
Aldo what about including the "Type in a query string to search for containers" Search box directly in the many bar next to the magnifying glass icon?  
My experience has been that I was using the containers page for all my searches and I did not notice the magnifying glass for a long time until a student mentioned she was mysteriously not getting the same search results I was ....
