### ISSUE TITLE
Dockerfile convert provides empty output

### ISSUE THREAD

**Issue by verdurin** [singularityhub/singularityhub.github.io#53]
## Link to Container Collection Log, Build, or Collection (in that order)

Trying to convert this Dockerfile:
https://raw.githubusercontent.com/rocker-org/rocker-versioned/master/rstudio/3.4.1/Dockerfile

### Behavior when Building Locally

I've tried manually converting...

### Error on Singularity Hub

There's no error shown, but no output either.
If the file cannot be parsed, an error message to that effect should appear.

### What do you think is going on?

Inability to cope with this particular Dockerfile (notably the run commands)?

**Comment by reikoch** [comment]
Maybe a related finding:
conversion of verse 3.4.1 from rocker-versioned seems to work, but when trying to run the image I see:

    $ singularity run /opt/R/singu/verse3.4.1.img
    s6-mkdir: warning: unable to mkdir /var/run/s6: Read-only file system

Could it be that RStudio docker images do not work under singularity?

**Comment by vsoch** [comment]
hey @verdurin ! Could you show me the container / log where this happened? I tried parsing with the local tool, and it does return a (non None) value when I strip away some of the extra &&. I think likely it's not erroring because it is returning a value, but likely one of the lines is parsed incorrectly. This tool hasn't been used much, so I'm glad you are using and happy to look into the bug for you!

**Comment by vsoch** [comment]
hey everyone! I'm going to disable the convert for now, since it's not properly developed. If you have ideas for version 2.0 (if you still want this) please open another issue, thanks!
