### ISSUE TITLE
Full-description (markdown) for containers?

### ISSUE THREAD

**Issue by dtrudg** [singularityhub/singularityhub.github.io#55]
One of the nice things about browsing docker hub is the presence of nice 'Full Description' instructions in Markdown for many containers. It'd be good to be able to add this type of thing for containers in singularity-hub, so full information / instructions for a container can be presented in the web interface that is used to discover singularity containers.

Unsure whether it'd be best for this description to be set with singularity-hub, or slurped from README(.md) or another file in the Git repo?

**Comment by yarikoptic** [comment]
Ideally just a way to edit that description straight on the singularity hub, since github repository might be more than just a Singularity file so description might be a bit misleading (e.g. in our case for NeuroDebian we described what that repository is exactly about within the scope of the entire project -- website, tools).

**Comment by vsoch** [comment]
Yep definitely can do that!

**Comment by vsoch** [comment]
Ok working on this - here are some things to discuss, because there are conflicting ideas here. There are a few things here:

 - collection descriptions (short summary)
 - collection README (if exist)
 - container description

The ability to edit a description or README obviously undoes any automatic parsing and vice versa. So for each of the above I'm curious about your opinion on:

 - if the field should be extracted automatically from Github, and if so, if it gets updated
 - given automatic updates, to what extent is manual change useful?

I see @yarikoptic use case - you would want to be able to customize the description. For this use case, likely we would want to grab an initial description, then make that final (and editable).

For @dctrud you are looking for more of the entire README, but it sounds less for seeing in singularity hub (this is much nicer to view in Github, and I prefer this even for Dockerfiles) but rather to be able to use the repo as a way to search.

So based on these two things, I would suggest the following:

- on the level of the collection - parse the description automatically and update when Github does (not content editable)
 - on the level of the container (the main view that people see) have the description originally as the collection description, but don't update from Github. Instead, let the user edit it as he/she wishes.
 - for the README, do some kind of processing or extraction to bring back tags for search (if this is the goal) OR try to extract the whole thing from a repo at build time and include with the image produced (not content editable).

Please let me know your thoughts!

**Comment by vsoch** [comment]
okay, I've implemented what I mentioned with the contenteditable description for a container:
![screenshot from 2017-10-06 19-38-41](https://user-images.githubusercontent.com/814322/31304062-27739bd0-aace-11e7-99af-e0a70b321d53.png)

It defaults to the collection description originally, and then is allowed for the owner to edit in the web interface. I haven't done anything special looking for READMEs yet, I'll wait for your feedback.

**Comment by yarikoptic** [comment]
Thanks!
I haven't yet looked into description for the collection... Editable for the container sounds like what I was after

**Comment by vsoch** [comment]
ok I'm going to mark this as finished unless there is other issue.
