### ISSUE TITLE
Bootstrapping failed without obvious error

### ISSUE THREAD

**Issue by mafeilong** [singularityhub/singularityhub.github.io#56]
## Link to Container Collection Log, Build, or Collection (in that order)

https://singularity-hub.org/containers/2900/log

### Behavior when Building Locally

Haven't tried this one yet.

### Error on Singularity Hub

```
/tmp/tmpab59_mm4/image
DEBUG:shub_builder:Built image: /tmp/tmpab59_mm4/75e3a4434985ae13ceb146d17f027ae6
INFO:shub_builder:Final time of build 2032 seconds.
ERROR:shub_builder:Image failed to bootstrap, cancelling build.
```
### What do you think is going on?

The messages of the build look good to me, however I still get an error message in the end and the build get cancelled.

**Comment by vsoch** [comment]
The build is huge - the instance might have run out of space (but we would see the message). 

```
Creating 32,768MiB image
```

Let's do the following:
- Try the build locally first
- If locally works, compare the size of the image to the size of the builder (100GB) and if 2 times the image size is greater than that, you should provide an estimated size so Singularity Hub doesn't need to do it.
 - If that doesn't work, then send me the recipe and I'll take a look at other things that might be going on.

**Comment by mafeilong** [comment]
Thanks @vsoch !
The local build was ok, however I got some error messages when I tried to reduce the image size following [this link](https://github.com/singularityware/singularity/issues/623).
```
e2fsck 1.42.9 (4-Feb-2014)
./fileHnGqYL: recovering journal
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Free blocks count wrong (8211917, counted=4016361).
Fix<y>? yes
Free inodes count wrong (2097141, counted=1971376).
Fix<y>? yes

./fileHnGqYL: ***** FILE SYSTEM WAS MODIFIED *****
./fileHnGqYL: 125776/2097152 files (12.0% non-contiguous), 4372247/8388608 blocks
eresize2fs 1.42.9 (4-Feb-2014)
Resizing the filesystem on ./fileHnGqYL to 4307486 (4k) blocks.
The filesystem on ./fileHnGqYL is now 4307486 blocks long.
```
Also, I cannot open the image built but can open the shrunk image, which seems to be related to this file system problem above.
```
> singularity shell zesty.img
ERROR  : Failed to mount image in (read only): Read-only file system
ABORT  : Retval = 255
```

**Comment by vsoch** [comment]
Okay - so if this is what is happening on Singularity Hub (the test is what you did (basically having the image run a simple echo) then it makes sense that the builder reported an unsuccessful built (because you don't have a working image). I don't know of any shrink functionality, I would suggest the following:

 - build a REALLY big image locally, big enough so you are sure it works
 - test that image. If it doesn't work, then you need to debug that first
 - if successful, calculate the size of the filesystem inside
 - build a new image of that size (with a little padding)
 - verify that image works

and THEN

- build on singularity hub, likely you will need the larger builder
- specify the size that worked for you locally

and then if the build still fails, we can say it's something about singularity hub and not an issue just creating the original image.

**Comment by vsoch** [comment]
hey @mafeilong if the build worked ok I'm going to close this issue. If you have trouble with singularity related things please post here --> https://www.github.com/singularityware/singularity/issues

**Comment by mafeilong** [comment]
Thanks @vsoch .
The problem seems related to the `apt-key` step which somehow broke the file system (still unsure why), and not a problem with singularity hub per se.
