### ISSUE TITLE
cannot see a repository in the list of new container to be built

### ISSUE THREAD

**Issue by cokelaer** [singularityhub/singularityhub.github.io#63]
### Error on Singularity Hub

I have added a Singularity file to this project: https://github.com/CancerRxGene/gdsctools (I have admin rights). 

In my singularity-hub page, I go to the container page (top right). Then, I click "add container".

Here we have the list of all connected repository below 'New Container Build'.

I cannot see the https://github.com/CancerRxGene/gdsctools  repository in the list. 

Do I need to change anything on github settings ?

### What do you think is going on?

Maybe I need to change something in the settings in the webhook or somewhere else ?

**Comment by vsoch** [comment]
hey @cokelaer ! This has happened to me too - and it's just because you have to give Singularity Hub access to the organization (it will see all repos regardless of having the file or not). For me the page is (on the second pagination) under https://github.com/settings/connections/applications

There should be a red X that you can give permission to change to green. Let me know if you have trouble!

**Comment by cokelaer** [comment]
So for bookeeping, 

- I went to [my github account (you have to log in) ](https://github.com/settings/connections/applications)
- On the right hand side, click on the "singularity-hub" link
- There you have all your organization and indeed there was a red cross. 

Thanks

**Comment by vsoch** [comment]
Thanks! Yeah it's embarrassing to admin, but I regularly have trouble finding this page. I always wind up somewhere else and have to start over, and then I'm sure that I had tried that... :)
