### ISSUE TITLE
usage page not complete

### ISSUE THREAD

**Issue by cokelaer** [singularityhub/singularityhub.github.io#74]
Usage (pull) is not clear enough on how do download a specific container

e.g.(https://www.singularity-hub.org/collections/114/usage)

For instance, container may be from different releases (branch / master) but I do  not see how to retrieve the specific develop version right now. 

similarly, I believe that in the previous hub version, there was a way to download a container thanks to its identifier, but I do not see that option in the usage page anymore.

thanks

**Comment by vsoch** [comment]
hey @cokelaer ! I used to have specifics for downloading a container on the single container page, but a user said it was not optimal because it would be expected to see on the collection page. Would you want to see two locations for usage - one on the collection and one on the page for a particular container build?

In the meantime - did you see the docs? https://github.com/singularityhub/singularityhub.github.io/wiki/Deploy#order-of-operations Basically, the digest can be a commit, a md5sum, or a branch.

**Comment by cokelaer** [comment]
The information missing for me (and therefore a potential user) was the "digest" method with the branch information. thanks

As for the usage page, I think the place is good. A link to the more details or adding this "digest" method could be useful. I close the issue since I got the relevant answer. thanks again for the quick feedback

**Comment by vsoch** [comment]
Sure thing! I'm working on some views now, and I'll add a link to the docs so users that want the details know how to get there. I should have it up within the next hour or so.

**Comment by vsoch** [comment]
okey doke:

![image](https://user-images.githubusercontent.com/814322/31863680-b6e57dd6-b705-11e7-8c07-8cde4923c0ed.png)

I didn't answer one of your questions - we did have a pull based on a container ID, but I decided to remove it because I couldn't guarantee that number and container association if the database needed to be re-created, for example. It was just a database index depending on when the container was added, and I thought best to remove for this time around in favor of using the digests (all captured by Github!)
