### ISSUE TITLE
Build phase "Setup" provides no feedback

### ISSUE THREAD

**Issue by TormodLandet** [singularityhub/singularityhub.github.io#75]
I have a container build stuck in "Setup" for a couple of days https://www.singularity-hub.org/collections/95
I tried at least twice and it is always stuck there. The Singularity-file in the root of the linked repository builds locally

I cannot find a link to see the commands being executed. I think it only shows up after the build is done? When the build is just hanging forever there is no way to get info about which command is actually hanging. Other online tools like CircleCI are easier to use in that regard, immediately once the build is out of the queue a link is provided to follow all the build steps live as they happen.

**Comment by vsoch** [comment]
Hey @TormodLandet !

I re-triggered the build of the current container and checked out the instance - it was failing and then stuck in setup due to missing most of its metadata, so I'm guessing this particular container got stuck in some of the crossfire of the last few days of server restarts and fixes. If you are interested in the log, it's rather uninteresting :o: 

```
Start Time: Tue Oct 24 09:44:42 UTC 2017.
fatal: repository 'None' does not exist
fatal: Not a git repository (or any of the parent directories): .git
WARNING commit not specified, setting to current 
ERROR Build file Singularity not found in repository
DEBUG False
LOG BUILD PARAMETERS:
repo_url is set to None
repo_id is set to None
response_url is set to None
bucket_name is set to singularityhub
tag is set to None
container_id is set to None
commit is set to None
branch is set to None
spec_file is set to None
logging_url is set to None
logfile is set to None
Found files are 
Return value of 1.
End Time: Tue Oct 24 09:44:48 UTC 2017.
```

I removed the buggy container and (from the back end) did a trigger, and it seems to be ok :) If this kind of thing happens ever (and hopefully as we catch and fix the various bugs that have come up it won't) it sometimes makes sense to delete the container and start it fresh. In this case you did the right thing to contact me so I could look more into it. Circle/Travis do have a nice web UI, but they don't have a person to go in and debug for you! :P 

Speaking of, I'm not sure what I can reasonably provide in terms of feedback from the builder - that would require either some kind of up in the level of the communication of the server and builder (something that would easily overload the server, and unlike Circle or Travis I'm not a huge company that can afford to scale the operation) or bringing the user to the builder, still windowed from the main interface.  Google has a really nice interface on the Google Cloud side:

![image](https://user-images.githubusercontent.com/814322/31937560-b9e34a8a-b869-11e7-911b-5f3df4230f3a.png)

and I asked them some time ago about an ability / API to get those plots, and their answer was something along the lines of "cool idea, why don't you make it?" I think it would be a great project, but I don't have the bandwidth atm!

The second option of the two above seems more reasonable given that the external server handles the additional load, but I'm not sure I have a good feeling for how to go about it. It would have to be that the builder opens a web port, starts an application, and then steams a log to it. Some questions:

- How would we handle https for all the different builders? 
- Probably web sockets are needed for a live stream from the builder to an interface?
- How would the main application seamlessly window or connect to the page?
- What is a reasonable way to scale this without substantial financial investment?

Do you have ideas or know what others do, without needing considerable scaling of the primary application? I really like the idea, but I'm not sure I can realistically support it given the limit on my resources. One thing I've thought about (and I'm wondering your thoughts on this) is how reasonable it would be to have a circleci / travis plugin that can be connected to do a repo, do a build, and then send some authenticated push of the image. I'm mostly nervous / against that kind of thing because it means sharing credentials everywhere. It's very different than the closed and protected world of Google Cloud :)

Here is your finished build! There was in fact a bug that I don't have a good explanation for - a missing variable in the metadata (that I've updated to be found / set if it doesn't exist). Once I added that in, the build finished successfully and the server went down. 

Let me know if you have any trouble here!

https://www.singularity-hub.org/containers/521

**Comment by TormodLandet** [comment]
Thanks!

I think, as a first step, having the results page available from the start would be very nice. The contents could just be something like "container build currently running, phase: Setup". Then, if someone goes there and manually requests an update, the backend could possibly pull in some info from the builder? At least that way the builders are not spamming the core infrastructure all the time, but it may be hard to pull info from the builder instead of the builder pushing info when it is done? Could the builder write a log file to some shared storage location also available to the web backend, or is it hard to create such a mount (safely) across all builders? A manual "get status" button could then just get back the contents of this file.

As for simple solutions, in this case a timeout on the setup step would have been enough, I think.

**Comment by vsoch** [comment]
Hey @TormodLandet - the request from the main server seems reasonable (assuming it's authenticated and someone can't use it to maliciously spam the instances).

That's exactly what the builder does do - it builds, as it does it outputs to a log file, it pings the instance immediately when the first pass at building is done (and the main server receives notice of the build) and then after this notice, the builder sends one final message to finish the build - and in this step the log file is uploaded to storage, the record of it sent to the main server, and it's that log file that is displayed for the user (actually read in from storage).

I think this was a rare buggy / errored case -it's never actually the case that a build should hang on setup, that means something else didn't happen and it got stuck. They usually go straight into "RUNNING" or minimally "PENDING." Setup is a very brief few seconds when  the container object is being created and metadata written to it, and then it's added to the container queue.

**Comment by vsoch** [comment]
@TormodLandet are there specific points you want to further discuss or can we close this issue?

**Comment by vsoch** [comment]
Thanks :)
