### ISSUE TITLE
Update the docs describing tags

### ISSUE THREAD

**Issue by jekriske** [singularityhub/singularityhub.github.io#80]
## Link to Container Collection Log, Build, or Collection (in that order)
https://github.com/singularityhub/singularityhub.github.io/wiki/Build-A-Container#naming-recipes

### Behavior when Building Locally

N/A

### Error on Singularity Hub

The tag determined by Singularity Hub does not follow the docs. 
Container URI is not readable in the GUI due to being cut off.

### What do you think is going on?

Vanessa says it's using tags from github. Instead of the older naming scheme.

> 1) remove the "tags" button from the container build interface,
> 2) add a clear indication of the container tag on the collection and container page, and
> 3) update the docs describing the tags, and 
> 4) investigate issue with parsing a tag with a slash in it

Example:
```
jekriske/r-base

Singularity           <= jekriske/r-base:latest (as expected)
R-3.4.2/
   Singularity.3.4.2  <= should be jekriske/r-base:3.4.2 according to the docs but instead
                         is parsed as jekriske/r-base:4.2/singularity.3.4.2 
```

```
jekriske/r-base

Singularity          <= jekriske/r-base:latest (as expected)
Singularity.3.4.2    <= parses correctly as jekriske/r-base:3.4.2 only when in the root directory. 
```

**Comment by vsoch** [comment]
Thanks for reporting this @jekriske ! The first issue with tags was not properly accounting for folders with `.` in them. It came down to changing:

```
parts = spec.split('.')
```
to

```
parts = os.path.basename(spec).split('.')
```

The tags was confusing because **now** they are topics from Github, and any custom that the user adds. You would only see them if your repository had tags, and it is rather confusing now that we have actual "tags." As we discussed earlier, I've removed them from the interface "container build" view, and it still is the case that if you **do** have topic tags from Github, they will show up at the top.

I've also added the clear designation of the tag on the container build page:

![image](https://user-images.githubusercontent.com/814322/32155918-a72865be-bcf7-11e7-939c-2feef76822fa.png)

Since the table in the collection view is to download the recipe file, I'm going to keep it as is for now. For docs, we didn't really have a page for metadata, so I added one, and made sure to describe what tags (actually) are:

https://github.com/singularityhub/singularityhub.github.io/wiki/Metadata

Take a look at all of the above and let me know if I missed anything!

**Comment by jekriske** [comment]
Looks good so far, some of the metrics of course don't show up on the table yet, like finished container size.

One concern might be if the future size metric reported is related to the label reported `"org.label-schema.build-size": "905MB"` I hope not.
For my particular image, this number is 15% larger than a sandbox build on a local FS (about 793 MB) and a great deal larger than the resulting squashfs image (282 MB).

BTW the `parts = os.path.basename(spec).split('.')` works great!

**Comment by vsoch** [comment]
okay, size is there!

![image](https://user-images.githubusercontent.com/814322/32182417-df91ac9c-bd53-11e7-9cee-f0aa2a3db343.png)

If you have an issue with the number itself, please report an issue on the main singularity board. The calculation is done with the Singularity software and the result produced by it via the builder is then shown here.

>> BTW the parts = os.path.basename(spec).split('.') works great!

woot!

**Comment by vsoch** [comment]
I'm going to close this issue, thanks for your help @jekriske.
