### ISSUE TITLE
Build stuck in pending state

### ISSUE THREAD

**Issue by alfpark** [singularityhub/singularityhub.github.io#86]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/collections/204

### Behavior when Building Locally

Builds fine.

### Error on Singularity Hub

Build is stuck, no progress is made. I've tried various things, delete, re-trigger, manual builds, nothing works. Everytime the `Date` always refers back to the first build. I even deleted the collection, re-created it and it picked up the `Date` from the old collection?

### What do you think is going on?

Don't know.

**Comment by vsoch** [comment]
hey @alfpark ! I'm debugging this for you now - I was doing work on the server this morning so likely something is off. For now don't touch the collection and I'll send an update soon.

**Comment by vsoch** [comment]
okay, I figured out the issue - I had a bug (fixed this morning) that was (sometimes) generating instance names with dashes, which is invalid for Google. However in fixing the bug I didn't update the builder metadata, and since these are unique names for a container --> builder, it was finding a builder in the "ACTIVE" queue (one that can no longer be referenced now that the bug is fixed) and then not creating a new builder with the fixed name. 

It's a hairball, but (at least the manual build) I triggered looks like it worked ok

https://www.singularity-hub.org/containers/708

Let's give a few more test tries and time for other users to report issues, it's always unlikely to be just right :)

**Comment by vsoch** [comment]
Looks like we are good? Closing issue!
