### ISSUE TITLE
Trigger build button does nothing

### ISSUE THREAD

**Issue by TormodLandet** [singularityhub/singularityhub.github.io#99]
Logged in, using Firefox 57.0.4 on Red Had Enterprise Linux. 
Viewing this page: https://www.singularity-hub.org/collections/95

I expected the trigger build button to add an active build to the list on the page

Clicking the refresh button on the page gives a message "No containers found in the pending queue"

**Comment by vsoch** [comment]
hey @TormodLandet ! I wanted to let you know I see the issue, and expect a little delay from me while I recover from a surgery. I'll hopefully be able to catch up with things soon, and please let me know if this is urgent!

**Comment by TormodLandet** [comment]
Take all the time you need. This was more for your information

**Comment by vsoch** [comment]
thank you :relaxed:

**Comment by vsoch** [comment]
hey @TormodLandet I'm alive! *tiny roar* I've fixed the issue with the button (the link just needed to be on the outside, instead of inside around the text) if you'd like to take a look. Note that it won't add immediately a build to the current page, it takes you to select the commit and Singularity recipe file to choose first!

**Comment by TormodLandet** [comment]
Thank you! Working now 😃 🥇

**Comment by stevekm** [comment]
Not working for me, on macOS under Firefox 58.0.2 (64-bit) and Chrome Version 65.0.3325.181 (Official Build) (64-bit). I clicked it several times but it does nothing

<img width="1298" alt="screen shot 2018-04-17 at 2 20 54 pm" src="https://user-images.githubusercontent.com/10505524/38888917-0b1d0cb8-424b-11e8-9213-903053071973.png">

**Comment by vsoch** [comment]
I don't think this issue is about the same button - to trigger a build you must select the commit to do, and click "Trigger Build." The button there I believe would be to rebuild an already existing container. If there is an error there I don't think that would work, but I haven't looked closely at it. Please try Triggering with the Trigger Build button and selecting a commit.

**Comment by stevekm** [comment]
I clicked the grey "Trigger Build" button shown in the image, to the right of the red Error button. I am not sure what you mean by 'selecting a commit'; I do not see any commit information anywhere. I am working from  this collection:
https://www.singularity-hub.org/collections/744

**Comment by vsoch** [comment]
Sorry I can be more clear. You first need to make your collection manual builds, meaning you can trigger, period. Click on settings:

![image](https://user-images.githubusercontent.com/814322/38889761-9f4e034a-424d-11e8-9999-197fe364a12d.png)

under the builder settings select Build Trigger to "Manual" and Save. A blue bar will confirm that the trigger is changed at the top.

![image](https://user-images.githubusercontent.com/814322/38889804-bce6042a-424d-11e8-9080-37e1391ed1b6.png)

Then back to your collection, you use the "Trigger Build" button to trigger a build.

![image](https://user-images.githubusercontent.com/814322/38889855-e03059b2-424d-11e8-8af6-7b3cd1943de5.png)

You can read more about the build options in the Help Documentation linked from the site: https://github.com/singularityhub/singularityhub.github.io/wiki/Meet-Builders

**Comment by stevekm** [comment]
Thanks. But this is prompting me to give the path to the Singularity file; I have many files in the repo at different locations on the master branch. They all build automatically when triggered by commit. There does not appear to be an option for this. For reference, the repo is [here](https://github.com/NYU-Molecular-Pathology/NGS580-nf/tree/master/containers)

![screen shot 2018-04-17 at 2 59 34 pm](https://user-images.githubusercontent.com/10505524/38890703-275c91b4-4250-11e8-91a8-d3b061b669fe.png)

**Comment by stevekm** [comment]
Also it appears that the 'Commit' build trigger is not working either, this collection has been ignoring auto-rebuilds on commit for weeks now it seems. I just did a commit, and the page automatically reloaded itself, but then did nothing.

**Comment by vsoch** [comment]
The trigger of a build doesn't happen for the entire repo, it's more of a targeted thing where you build a specific file of interest. For the commit build trigger, if you set it to build Manually, it's not going to build on commit. Can you confirm that it's set to commit, and then look in your webhook settings to see the response from the server?

**Comment by vsoch** [comment]
hey @stevekm I just looked into a few things:
 
 - when the collection is set to manual (note I turned it on manual and cleaned up your setup builds) it *does* in fact build. If you look here --> https://www.singularity-hub.org/containers/2145/log the error you are hitting is the whiteout / aws header issue that has been fixed in more development versions of singularity, but not yet on shub. This means that this should work for you when we update the builders.
 - I am not sure about why so many builds would go into setup and freeze, but my best guess is that since the flow is dependent on one finishing and triggering the next, you have *so* many containers in one repository that there was some kind of conflict or race condition. I would also want to check if the webhook on your repo's end was received (and there were no weird messages returned).

So the stopping point right now is the layers you are pulling - they are always going to fail given that one of them isn't actually .tar.gz. We can best hope that Singularity is released with the next version soon to fix this up! When that is fixed we can address the reason for the commits not working as expected. I am sorry that you are having trouble!

**Comment by stevekm** [comment]
Thanks for the help. So should I just wait for updates to Singularity & Singularityhub then? I can build the container images locally and transfer the image files to my remote servers, but thats a little tedious, thus Singularityhub. Also maybe this issue should be moved to a new Issue for future followups?

**Comment by vsoch** [comment]
Yes to both! Let's 1) make new issue for follow up and 2) wait for update to Singularity (and the builders).
